server:
  port: 8761

spring:
  application:
    name: discovery-server

  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
    livereload:
      enabled: true

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false